### ISSUE TITLE
riddle() function in lib.py throwing index error.

### ISSUE THREAD

**Issue by AnkithAbhayan** [AnkithAbhayan/python-chat-bot#22]
full output :-
```
D:\git repo\chat-bot>python main.py
Hi, I'm your friend you can ask me questions but not sure I can answer all
If you are enough having fun with me say 'stop'
loading database
tell me your question plz.. riddle
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    data.get(i)()
  File "D:\git repo\chat-bot\lib.py", line 156, in riddle
    ran=choice(range(len(answers)))
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

D:\git repo\chat-bot>
```

**Comment by Sai-Prabhav** [comment]
fixed

**Comment by AnkithAbhayan** [comment]
created a pull request or something?

**Comment by AnkithAbhayan** [comment]
yup, its working.
closing the issue now
-Ankith
