### ISSUE TITLE
lcm issue

### ISSUE THREAD

**Issue by Sai-Prabhav** [AnkithAbhayan/python-chat-bot#32]
the error comes only when we input same number

PS C:\Users\vvrao\OneDrive\Desktop\sinnik_school\code\python-chat-bot-main\python-chat-bot-main> & C:/Users/vvrao/miniconda3/python.exe c:/Users/vvrao/OneDrive/Desktop/sinnik_school/code/python-chat-bot-main/python-chat-bot-main/main.py
Hi, I'm your friend you can ask me questions but not sure I can answer all 
If you are enough having fun with me say 'stop'  
loading database
tell me your question plz.. test 123
find lowest common multiple
enter first number:12
enter second number:12
Traceback (most recent call last):
  File "c:/Users/vvrao/OneDrive/Desktop/sinnik_school/code/python-chat-bot-main/python-chat-bot-main/main.py", line 65, in <module>
    values()
  File "c:\Users\vvrao\OneDrive\Desktop\sinnik_school\code\python-chat-bot-main\python-chat-bot-main\lib2.py", line 353, in LowestCommonMultiple
    test_small_num = small_num
UnboundLocalError: local variable 'small_num' referenced before assignment

**Comment by AnkithAbhayan** [comment]
I have fixed the error. update the code and run again. its working for me.
